import Head from 'next/head'
import { Sidebar } from '@/components/Sidebar'

export default function Home () {
  return (
    <div className='bg-black h-screen overflow-hidden'>
      <Head>
        <title>Spotify clone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Sidebar />
        {/* Center */}
      </main>
      <div>{/* Player */}</div>
    </div>
  )
}
