import Head from 'next/head'
import { Sidebar } from '@/components/Sidebar'
import { Center } from '@/components/Center'
import { getSession } from 'next-auth/react'

export default function Home () {
  return (
    <div className='bg-black h-screen overflow-hidden'>
      <Head>
        <title>Spotify clone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex'>
        <Sidebar />
        <Center />
      </main>
      <div>{/* Player */}</div>
    </div>
  )
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context)
  return {
    props: {
      session
    }
  }
}
